spring:
  cloud:
    config:
      server:
        native:
          search-locations: 'classpath:/config'
    loadbalancer:
      ribbon:
        enabled: false


server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always